const EARTH_RADIUS_IN_METERS = 6371000;
const DISTANCE_VERIFICATION_STATUS=Object.freeze({
    VERIFIED: "VERIFIED",
    LOW_ACCURACY: "LOW_ACCURACY",
    OUT_OF_RANGE: "OUT_OF_RANGE",
    NO_LOCATION: "NO_LOCATION"
});
module.exports = { EARTH_RADIUS_IN_METERS, DISTANCE_VERIFICATION_STATUS  };
